despawn-radius: 80
shiny-rate: 2000.0
ultra-space-shiny-rate-multiplier: 0.5
hidden-ability-rate: 50.0
ultra-space-hidden-ability-multiplier: 0.5
legendary-spawn-ticks: 25000
legendary-spawn-chance: 1.0
spawn-ticks-player-multiplier: 0.10000000149011612
spawn-levels-closer-to-player-levels: false
spawn-levels-increase-in-caves: false
cave-max-multiplier: 0
transform-to-ditto-on-catch: 0.001
meltan-spawn-chance: 3072
meltan-transform-chance: 0.25
can-transform-to-ditto-on-catch:
- Pidgey
- Rattata
- Gastly
- Zubat
- Mankey
- Yanma
- Hoothoot
- Sentret
- Zigzagoon
- Gulpin
- Whismur
- Taillow
- Remoraid
- Starly
- Drifloon
- Burmy
gigantamax-factor-rate: 512.0
ultra-space-gigantamax-factor-modifier: -1.0
allow-legendary-spawn: true
legendary-despawn-ticks: 6000
display-legendary-global-message: true
do-legendary-raid-event: true
use-recent-level-moves: true
despawn-on-flee-or-loss: false
bell-success-chance: 0.01
bell-inclusion-range: 10
lure-flute-duration: 180
lure-flute-level-modifier: 10
blocked-generations: []
spawn-zygarde-cells: true
level-distance:
    spawn-levels-by-distance: false
    max-level-by-distance: 0
    distance-per-level: 0
wild-spawning:
    entities-per-player: 50
    spawns-per-pass: 2
    spawn-frequency: 120.0
    minimum-distance-between-spawns: 4.0
    minimum-distance-from-centre: 16
    maximum-distance-from-centre: 64
    horizontal-track-factor: 0.0
    vertical-track-factor: 0.0
    horizontal-slice-radius: 9
    vertical-slice-radius: 8
    maximum-spawned-pokemon: 3000
    maximum-spawned-flying-pokemon: 500
    maximum-spawned-flying-pokemon-per-player: 45
boss-spawning:
    boss-rate: 256.0
    ultra-space-boss-modifier: 0.5
    bosses-always-mega-if-possible: true
    boss-spawn-ticks: 10000
    boss-spawn-chance: 0.30000001192092896
poke-loot:
    spawn-normal: true
    spawn-hidden: true
    spawn-grotto: true
    spawn-rate: NORMAL
    spawn-mode: FCFS
    loot-time: 24
poke-stop:
    enabled: true
    loot-time: 24
ultra-space-hoard-spawn-rate: 0.4000000059604645
spawn-levels-increase-in-ultra-space: true
ultra-space-level-multiplier: 2.0
meltan-box-spawn-rate: 20
meltan-box-spawn-radius: 15
meltan-box-initial-scraps-count: 4
meltan-box-scraps-multiplier: 1.8
meltan-box-open-duration-millis: 100000
meltan-box-cooldown-duration-millis: 3000000
always-aggressive-dimensions:
- pixelmon:ultra_space
horde-battle-dimensions:
- pixelmon:ultra_space
spawning-disabled-dimensions: []
shiny-charm-rate-multiplier: 3.0
ultra-space-horde-spawn-rate: 0.4000000059604645
player-tracking-spawner-spawn-collection-rate: 100
